version: "3.8"

services:
  backend:
    build: backend/.
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/api
    container_name: airbus_api
    restart: on-failure
    env_file:
      - ./.env
    user: ${CURRENT_UID}

  frontend:
    build:
      context: ./frontend/
      args:
        API_URL: $api_url
        BASE_URL: $base_url
    stdin_open: true
    container_name: airbus_ui
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/ui
    env_file:
      - ./.env
    user: ${CURRENT_UID}
