export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const SET_DETAIL_PRODUCT = "SET_DETAIL_PRODUCT";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
